var searchData=
[
  ['random_20number_20generation_0',['Random Number Generation',['../group__rng.html',1,'']]],
  ['random_20parameters_1',['Using Random Parameters',['../writing_tests.html#bp_random_params',1,'']]],
  ['randomize_5fbuf_2',['RANDOMIZE_BUF',['../group__memory.html#ga9b47d3dbddf9465c6bc1a0f34f9cabc9',1,'utils.h']]],
  ['randomize_5fbuf_5frect_3',['RANDOMIZE_BUF_RECT',['../group__bufrect.html#ga3abfe25c549cceae1852fc25021111d2',1,'utils.h']]],
  ['raw_20measurements_20right_20chart_4',['Raw Measurements (right chart)',['../benchmarking.html#adv_raw_measurements',1,'']]],
  ['realistic_20test_20data_5',['Realistic Test Data',['../benchmarking.html#bp_realistic',1,'']]],
  ['recommended_6',['Modern API (Recommended)',['../writing_tests.html#modern_api',1,'']]],
  ['recommended_7',['Meson using submodules (recommended)',['../getting_started.html#meson_submodules',1,'']]],
  ['rectangular_20buffer_20helpers_8',['Rectangular Buffer Helpers',['../group__bufrect.html',1,'']]],
  ['regression_9',['Linear Regression',['../benchmarking.html#bench_regression',1,'']]],
  ['regression_20detection_10',['Regression Detection',['../benchmarking.html#interp_regression',1,'']]],
  ['repeat_11',['repeat',['../structCheckasmConfig.html#a8a999efdd89fac0fa78a48c015363bba',1,'CheckasmConfig']]],
  ['report_20deep_20dive_12',['HTML Report Deep Dive',['../benchmarking.html#adv_html',1,'']]],
  ['reporting_13',['Reporting',['../writing_tests.html#adv_failure',1,'Custom Failure Reporting'],['../index.html#example_errors',1,'Error Reporting']]],
  ['reports_14',['Organizing Reports',['../writing_tests.html#bp_reporting',1,'']]],
  ['reproducible_20benchmarks_15',['Reproducible Benchmarks',['../benchmarking.html#tips_reproducible',1,'']]],
  ['resolution_16',['Timer Resolution',['../benchmarking.html#adv_timer',1,'']]],
  ['results_17',['Results',['../benchmarking.html#bench_export',1,'Exporting Results'],['../benchmarking.html#bench_interpreting',1,'Interpreting Results']]],
  ['right_20chart_18',['Raw Measurements (right chart)',['../benchmarking.html#adv_raw_measurements',1,'']]],
  ['run_19',['3. Build and Run',['../getting_started.html#quick_start3',1,'']]],
  ['running_20benchmarks_20',['Running Benchmarks',['../benchmarking.html#bench_cli',1,'']]],
  ['runs_21',['Geometric Mean for Multiple Runs',['../benchmarking.html#bench_geometric',1,'']]]
];
