name: Compile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v5.0.0
      with:
        cache: 'pip'
    - name: Install meson
      run: pip install meson ninja
    - name: Install nasm
      run: sudo apt-get install nasm
    - uses: actions/checkout@v3
    - name: Configure
      run: meson setup build
    - name: Build
      run: meson compile -C build
